name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        args: release
      env:
          GITHUB_TOKEN: ${{ secrets.GH_GO_RELEASER_TRY }}
